name: Bobbbykong

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the Bobbykong/builder container
      run: |
        docker run \
        -v ${{ GitHub.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        Bobbykong/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
